baseURL = "https://www.tylerquinlivan.com/"
languageCode = "en-us"
title = "Tyler Quinlivan"
theme = "hugo-theme-console"
sectionPagesMenu = "main"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated pulse fast"

  # Reference any custom CSS I make in the layouts/partials/header.html file
  custom_css = ["quote_style.css", "code_style.css"]

  #[[params.navlinks]]
  #name = "/posts/"
  #url = "posts/"

  [[params.navlinks]]
  name = "/posts/"
  url = "posts/"

  [[params.navlinks]]
  name = "/arnotts_biscuits/"
  url = "arnotts/"

  [[params.navlinks]]
  name = "~/.about"
  url = "about/"

  [[params.navlinks]]
  name = "~/.contact"
  url = "contact/"
